framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: global_soft/symfony_create_twig_tag

        # Redis
        app: cache.adapter.redis
        default_redis_provider: redis://localhost

        pools:
            cache.app_redis_cache:
                adapter: cache.adapter.redis
                tags: true
                provider: app.redis_provider
                default_lifetime: 3600
